apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
# these are deployment labels
  labels:
    purpose: headless-svc-demo
    project: safety
spec:
  replicas: 4
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: headless-svc-demo
      project: safety
    # pod definition
  template: 
    metadata:
      labels:
        purpose: headless-svc-demo
        project: safety
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1 
kind: Service
metadata: 
  name: nginx
spec:
  selector:
        purpose: headless-svc-demo
        project: safety
  ports:
    - protocol: TCP
      port: 80 ## services port
      targetPort: 80 ## container port